### ISSUE TITLE
2024.02.27

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/real-time-cloud#25]
----
## 2024.02.27 Agenda/Minutes
--- 
Time 0800 / 1600 (BST) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Chair – Adrian Cockcroft 
- Chair - Pindy Bhullar (UBS)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://zoom.us/rec/share/OrAbMHaw_INOXABVkxwDv0r8MSdh2E0GZkuEjbR_WbGMpmE5NnD7DiVUgsckoCyj.eAN9SvLFhfZWpHBm?startTime=1709049602000). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/real-time-cloud/issues/23)

## Renewable Energy Percentage
- [x] Defining language for the column headers

**Action Item:** Members requested to assist in defining column headers [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet

## Open Issues [Project Board](https://github.com/orgs/Green-Software-Foundation/projects/34/views/1?layout=board) 
- [ ] #20
- [ ] #19
- [ ] #12 
- [ ] #7 
- [ ] #4 
- [ ] #2 

## Discussion Board
- [x] Review [miro dataflow in detail](https://miro.com/app/board/uXjVM1o59N4=/?share_link_id=183104215286)
  - Continue to review and approve the proposed Scope.

## Milestone Objective
- [x] Outline of proposed milestone dates

## AOB
- [x] Any topics members would like to submit

## Next Meeting 
- [x] 12th Mar

## Adjourn 
- [x] Motion to adjourn
--------

## Meeting Action Items / Standing Agenda / Future Agenda submissions / Links
- [x] The current sheet of raw data is here - this contains guesses for current ranges and is a work in progress at this point
https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit?usp=sharing

**Comment by seanmcilroy29** [comment]
Attended

**Comment by adrianco** [comment]
Attended

**Comment by seanmcilroy29** [comment]
**MoM**

**Action Item**
- [ ] Members to review and comment on the [RTC Cloud Region Impact Framework Documentation](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.hrk0bx7hun4)
- [ ] Add a column for Google's 24/7 carbon intensity data once it is approved for publishing.
- [ ] Members requested to assist in defining column headers [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet
- [ ]  Fill in missing data columns in the spreadsheet, including PUE data and IEA annual average numbers.
- [ ] Get the spreadsheet definitions finalized so we can start filling in the data. Clarify column names and descriptions.
- [ ] Review and comment on [https://miro.com/app/board/uXjVM1o59N4=/](Scope Flow)

**Standardizing cloud provider data for carbon emissions tracking.**
Group discuss the efforts made by cloud providers to reduce their carbon emissions. During the discussion, they focused on Google's API, which has been considered a gold standard in this regard. It was suggested that they should identify standardized sources for cloud carbon footprint data. It was proposed that they establish a standard for collecting data on power usage in the cloud. They plan to start with a small ask to get data on an annual basis from each of the three major cloud providers. Tim outlines he’s been conducting monthly sessions with sustainability product owners from Google, Amazon, and Microsoft to get their input on the data and establish pathways for requesting it. The group discuss working towards a more efficient and sustainable future for cloud computing.

**Carbon footprint and sustainability in cloud computing.**
Adrian discusses challenges with estimating a company's carbon footprint, including issues with data quality and the need for better models to reflect optimizations. Adrian and Tim are analysing cloud provider data on power generation and carbon intensity, focusing on data centres and workload levels. They have identified various data sources and methods for measuring carbon footprint, including PPA, carbon intensity, and embodied carbon schema definition.

**Collecting and analysing power consumption data in data centres.**
The team discussed power consumption in data centres and expressed interest in exploring the topic further. Tim suggests using management consoles in the data centre to gather power statistics, which Adrian agrees to look into. The group discuss the difficulty of obtaining real-time power data for every machine in a cloud environment. Adrian suggests that it may be a lot of work for cloud providers to collect and share this data. Tim suggests there may be existing telemetry data that could be surfaced to customers, but it's unclear who collects this data or how it's stored.

**Carbon emissions and energy usage in cloud computing.**
The Group discuss the complexity of carbon footprint calculations for cloud providers, including different metrics and data sources.  Adrian: Google's effective carbon intensity is 354, based on hourly data from electricity maps.  Adrian and Vincent discuss using a cloud provider region to obtain relevant metadata for carbon intensity calculations. The group agrees to use a document to determine the appropriate metadata for an impact framework.

**Carbon emissions metrics and reporting.**
Adrian discusses carbon intensity and data availability for energy reporting. The group discuss the importance of aligning on net zero definitions in the carbon market. The team discuss the naming conventions for carbon metrics, focusing on clarity and consistency.
