### ISSUE TITLE
2024.04.09

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/real-time-cloud#36]
----
## 2024.04.09 Agenda/Minutes
--- 
Time 0900 (PT) / 1600 (BST) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Chair – Adrian Cockcroft 
- Chair - Pindy Bhullar (UBS)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://zoom.us/rec/share/OrAbMHaw_INOXABVkxwDv0r8MSdh2E0GZkuEjbR_WbGMpmE5NnD7DiVUgsckoCyj.eAN9SvLFhfZWpHBm?startTime=1709049602000). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/real-time-cloud/issues/23)

## Renewable Energy Percentage
- [ ] Defining language for the column headers

**Action Item:** Members requested to assist in defining column headers [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet
- [RTC Cloud Region Impact Framework Documentation](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.hrk0bx7hun4m)

## Open Issues [Project Board](https://github.com/orgs/Green-Software-Foundation/projects/34/views/1?layout=board) 
- [ ] #31
- [ ] #32
- [x] #33 
- [x] #34 
- [ ] #35 
- [ ] #29 
- [x] #28  
- [x] #27 
- [ ] #20
- [ ] #19
- [ ] #12 
- [ ] #4 

## Discussion Topic
- [ ] Energy

## Previous Meeting Action Items

- [ ] Create specific issues for each ask to cloud providers
- [ ]  Escalate issues to cloud provider contacts to get carbon and energy data
- [ ]  Follow up in 1-2 weeks on any progress with Microsoft contact
- [ ]  Look into getting publicly available annual grid carbon intensity data
- [ ]  Clarify if Google's carbon intensity data is helpful for CI or not
- [ ]  Check internally on providing GCP PUE estimates
- [ ] Figure out naming conventions for metrics like hourly vs 24/7
- [x]  Add columns in the spreadsheet for Electricity map and WattTime data
- [ ]  Fill in missing data in a spreadsheet for regions
- [ ]  Add geolocation data for regions in the spreadsheet

## Discussion Board
- [ ] Review [miro dataflow in detail](https://miro.com/app/board/uXjVM1o59N4=/?share_link_id=183104215286)
  - Continue to review and approve the proposed Scope.

## Milestone Objective
- [ ] Outline of proposed milestone dates

## AOB
- [ ] Any topics members would like to submit

## Next Meeting 
- [ ] 23th Apr

## Adjourn 
- [ ] Motion to adjourn
--------

 Members to review and comment on the [RTC Cloud Region Impact Framework Documentation](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.hrk0bx7hun4)
 Add a column for Google's 24/7 carbon intensity data once it is approved for publishing.
 Members requested to assist in defining column headers [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet
 Fill in missing data columns in the spreadsheet, including PUE data and IEA annual average numbers.
 Get the spreadsheet definitions finalized to start filling in the data. Clarify column names and descriptions.
 Review and comment on [Scope Flow](https://miro.com/app/board/uXjVM1o59N4=/)

**Comment by adrianco** [comment]
Attended

**Comment by coopere** [comment]
Attended

**Comment by ash-ara** [comment]
Attended

**Comment by alexander-kroll** [comment]
Attended

**Comment by seanmcilroy29** [comment]
**MoM**
Adrian opens the meeting at 0900 (PT) / 1600 (BST)

Data sources for cloud infrastructure efficiency analysis.
Cooper provided updates on data sources for PUE analysis, including annual and quarterly data from environmental reports. Adrian and Cooper discussed cloud region names and cleanup. Adrian mentioned an upcoming meeting with Chris Walker from AWS.

Data analysis and energy usage in cloud computing.
Adrian and Sean discussed the need to assign a unique identifier to each data point in a dataset. Adrian is looking for help turning a spreadsheet into a data source for the impact framework. Sean will chat with Joseph to see if he has any feedback on the matter. Adrian notes the growing importance of GPU usage in energy consumption, with a need for better tracking and estimation methods.

Sustainability in cloud computing.
Cooper suggests optimizing job scheduling for maximum utilization is more effective at the data centre than at the individual user level.

Action Items
- [ ] Follow up with Thomas from GCP to get an update on collecting Azure PUE data methodology.
- [ ] Follow up with Chris Walker from AWS to get an update on any new PUE data that may be available.
- [ ] Create an issue to define the process for converting the spreadsheet data into an impact framework data source. Assign the issue to Joseph.
- [ ] Research GPU power metrics and interfaces and find an expert to help with collecting GPU power data.
- [ ] Reach out to contacts at NVIDIA to explore sharing GPU power curves and metrics.
- [ ] Map the Google annual environmental report region names to the actual cloud region names and clean up the data.
- [ ] Invite Marco Stiller and/or Chris from the Green Software Foundation to the next meeting to discuss their carbon footprint tool.

**Comment by tdigeser91** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended from 4.30pm
